openapi: "3.0.0"
info:
  version: 1.0.0
  title: riskfactor
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/
tags:
  - name: messages
    description: Messages API
paths:
  '/messages/{id}':
    get:
      summary: Returns the message with the given ID
      description: Returns the message with the given ID
      operationId: getMessageById
      tags:
        - messages
      parameters:
        - name: id
          in: path
          description: ID of the message
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/MessageResponse'
        '500':
          description: Error response
components:
  responses:
    MessageResponse:
      description: Successful response with the message
      content:
        application/json:
          schema:
            title: MessageResponse
            description: Representation of a message
            type: object
            properties:
              data:
                type: object
                properties:
                  type:
                    type: string
                  id:
                    type: string
                  attributes:
                    type: object
                    properties:
                      text:
                        type: string
                      lastModified:
                        type: string
                        format: date-time
                    required:
                      - text
                      - lastModified
                required:
                  - type
                  - id
                  - attributes
            required:
              - data
